scan_filter_chain:
- name: shadows
  type: ScanShadowsFilter
  params:
    min_angle: 0
    max_angle: 270
    neighbors: 20
    window: 1
- name: range
  type: LaserScanRangeFilter
  params:
    lower_threshold: 0.4
    upper_threshold: .inf

- type: LaserArrayFilter
  name: laser_median_filter
  params: 
    range_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10
    intensity_filter_chain:
      - name: median_5
        type: MultiChannelMedianFilterFloat 
        params:
          number_of_observations: 5
          unused: 10
